package geotiff

import (
	"encoding/binary"
	"math"
	"os"
	"path/filepath"
	"testing"
)

const (
	fixtureW, fixtureH = 53, 37
	fixtureNoData      = -9999
)

// The fixtures are generated by testdata/gen.sh and cover the compression,
// predictor, layout and byte-order combinations found in GeoTIFFs.
func TestDecodeFixtures(t *testing.T) {
	f32 := readExpected(t, "expected_f32.raw", 4, func(b []byte) float32 {
		return math.Float32frombits(binary.LittleEndian.Uint32(b))
	})
	i16 := readExpected(t, "expected_i16.raw", 2, func(b []byte) float32 {
		return float32(int16(binary.LittleEndian.Uint16(b)))
	})

	tests := []struct {
		file string
		want []float32
	}{
		{"f32_none.tif", f32},
		{"f32_lzw.tif", f32},
		{"f32_lzw_pred3_strips.tif", f32},
		{"f32_deflate_pred3_tiled.tif", f32},
		{"f32_deflate_strips.tif", f32},
		{"f32_lzw_pred3_be.tif", f32},
		{"i16_lzw_pred2.tif", i16},
		{"i16_deflate_pred2_be_tiled.tif", i16},
	}
	for _, tt := range tests {
		t.Run(tt.file, func(t *testing.T) {
			r, err := Open(filepath.Join("testdata", tt.file))
			if err != nil {
				t.Fatal(err)
			}
			if r.Width != fixtureW || r.Height != fixtureH {
				t.Fatalf("size = %dx%d, want %dx%d", r.Width, r.Height, fixtureW, fixtureH)
			}
			if r.OriginX != 350000 || r.OriginY != 5700037 || r.PixelWidth != 1 || r.PixelHeight != 1 {
				t.Errorf("georef = origin (%v, %v) pixel (%v, %v)", r.OriginX, r.OriginY, r.PixelWidth, r.PixelHeight)
			}
			for i, want := range tt.want {
				got := r.Data[i]
				if want == fixtureNoData {
					if !math.IsNaN(float64(got)) {
						t.Fatalf("pixel %d = %v, want NaN (nodata)", i, got)
					}
				} else if got != want {
					t.Fatalf("pixel (row %d, col %d) = %v, want %v", i/fixtureW, i%fixtureW, got, want)
				}
			}
		})
	}
}

func TestDecodeRejectsGarbage(t *testing.T) {
	good, err := os.ReadFile("testdata/f32_none.tif")
	if err != nil {
		t.Fatal(err)
	}
	bigtiff := append([]byte("II\x2b\x00"), good[4:]...)

	tests := map[string][]byte{
		"empty":     nil,
		"not tiff":  []byte("this is definitely not a tiff file"),
		"bigtiff":   bigtiff,
		"truncated": good[:len(good)/2],
		"bad IFD":   append(append([]byte{}, good[:4]...), 0xff, 0xff, 0xff, 0x7f),
	}
	for name, data := range tests {
		if _, err := Decode(data); err == nil {
			t.Errorf("%s: Decode succeeded, want error", name)
		}
	}
}

// Every prefix of a valid file must fail cleanly rather than panic.
func TestDecodeTruncationNeverPanics(t *testing.T) {
	for _, name := range []string{"f32_lzw_pred3_strips.tif", "i16_deflate_pred2_be_tiled.tif"} {
		good, err := os.ReadFile(filepath.Join("testdata", name))
		if err != nil {
			t.Fatal(err)
		}
		for n := 0; n < len(good); n += 7 {
			_, _ = Decode(good[:n])
		}
	}
}

func readExpected(t *testing.T, name string, size int, conv func([]byte) float32) []float32 {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	if len(b) != fixtureW*fixtureH*size {
		t.Fatalf("%s: %d bytes, want %d", name, len(b), fixtureW*fixtureH*size)
	}
	out := make([]float32, fixtureW*fixtureH)
	for i := range out {
		out[i] = conv(b[i*size:])
	}
	return out
}
